### ISSUE TITLE
ZipFile invalid LOC header (bad signature)

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/atplug#3]
```
        Caused by: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
                at java.base/java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(ZipFile.java:920)
                at java.base/java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:931)
                at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:448)
                at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
                at java.base/java.io.FilterInputStream.read(FilterInputStream.java:132)
                at java.base/java.io.FilterInputStream.read(FilterInputStream.java:106)
                at kotlin.io.ByteStreamsKt.copyTo(IOStreams.kt:106)
                at kotlin.io.ByteStreamsKt.copyTo$default(IOStreams.kt:103)
                at com.diffplug.atplug.PlugRegistry$Companion.parseComponent$atplug_runtime(PlugRegistry.kt:41)
                at com.diffplug.atplug.PlugRegistry$Eager.<init>(PlugRegistry.kt:77)
                at com.diffplug.atplug.PlugRegistry$Companion$instance$1.invoke(PlugRegistry.kt:23)
                at com.diffplug.atplug.PlugRegistry$Companion$instance$1.invoke(PlugRegistry.kt:23)
                at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
                at com.diffplug.atplug.PlugRegistry$Companion.registerSocket$atplug_runtime(PlugRegistry.kt:26)
                at com.diffplug.atplug.SocketOwner$EphemeralByDescriptor.<init>(SocketOwner.kt:46)
                at com.diffplug.pane.entity.EPathRightClick$Socket.<init>(EPathRightClick.java:101)
                at com.diffplug.pane.entity.EPathRightClick.<clinit>(EPathRightClick.java:97)
```

**Comment by nedtwigg** [comment]
Fixed by #2.
